// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID             int32
	Type           int32
	Value          int32
	State          pgtype.Text
	CreationTime   pgtype.Timestamp
	LastUpdateTime pgtype.Timestamp
}
